numero1 = float(input("insira o primeiro número: "))
numero2 = float(input("insira o segundo número: "))

print(numero1 + numero2)
print(numero1 - numero2)  
print(numero1 / numero2)  
print(numero1 * numero2)  
print(numero1 ** numero2)  
print(numero1 // numero2)    
print(numero1 % numero2)    
